
- hosts: all
  remote_user: root
  
  vars:
    reboot_machines: true
  
  tasks:
    - name: Set JAVA_TOOL_OPTIONS to prevent CVE-2021-44228
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^JAVA_TOOL_OPTIONS'
        line: 'JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true' 
      when:
        - ansible_facts['system'] == "Linux"

    - name: Set JAVA_TOOL_OPTIONS to prevent CVE-2021-44228 on Windows
      win_environment:
        state: present
        name: JAVA_TOOL_OPTIONS
        value: -Dlog4j2.formatMsgNoLookups=true
        level: machine
      when: 
      - ansible_facts['system'] == "Win32NT"   
    
    - name: Reboot the Linux server
      reboot:
        reboot_timeout: 10
      when: 
      - reboot_machines
      - ansible_facts['system'] == "Linux"

    - name: Reboot Windows server
      ansible.windows.win_reboot:
      when: 
      - reboot_machines
      - ansible_facts['system'] == "Win32NT"   
     
  
